# Generated by Django 4.1.3 on 2024-02-08 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addapp', '0003_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
