# Generated by Django 4.1.3 on 2024-02-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
